# Generated by Django 4.1.2 on 2022-10-31 16:56

from django.db import migrations, models
import wiredAPI.models


class Migration(migrations.Migration):

    dependencies = [
        ('wiredAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to=wiredAPI.models.user_profile_directory_path),
        ),
    ]
