# Generated by Django 4.1.2 on 2022-11-07 13:37

from django.db import migrations, models
import wiredAPI.models.user_model


class Migration(migrations.Migration):

    dependencies = [
        ('wiredAPI', '0002_alter_user_bio_alter_user_display_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_pic',
            field=models.ImageField(blank=True, default='no bio', null=True, upload_to=wiredAPI.models.user_model.user_profile_directory_path),
        ),
    ]
