# Generated by Django 4.1.2 on 2022-11-07 13:40

from django.db import migrations, models
import wiredAPI.models.user_model


class Migration(migrations.Migration):

    dependencies = [
        ('wiredAPI', '0003_alter_user_display_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, default='no bio', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_pic',
            field=models.ImageField(blank=True, null=True, upload_to=wiredAPI.models.user_model.user_profile_directory_path),
        ),
    ]
