# Generated by Django 4.1.2 on 2022-11-12 19:10

from django.db import migrations, models
import wiredAPI.models.user_model
import wiredAPI.storage


class Migration(migrations.Migration):

    dependencies = [
        ('wiredAPI', '0005_alter_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_pic',
            field=models.ImageField(blank=True, null=True, storage=wiredAPI.storage.OverwriteStorage(), upload_to=wiredAPI.models.user_model.user_profile_directory_path),
        ),
    ]
