# Generated by Django 4.1.2 on 2022-11-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiredAPI', '0007_chat_message_videomessage_textmessage_imagemessage_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chat',
            new_name='Contact',
        ),
        migrations.RemoveField(
            model_name='textmessage',
            name='message',
        ),
        migrations.RemoveField(
            model_name='textmessage',
            name='user',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='chat_id',
            new_name='contact_id',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='title',
            new_name='display_name',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='chat',
            new_name='reciver',
        ),
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ChatParticipant',
        ),
        migrations.DeleteModel(
            name='TextMessage',
        ),
    ]
