# Generated by Django 4.1.2 on 2022-11-14 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiredAPI', '0009_contact_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='user',
            new_name='contact_user',
        ),
    ]
