# Generated by Django 4.1.2 on 2022-11-14 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiredAPI', '0010_rename_user_contact_contact_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='reciver',
            new_name='contact',
        ),
    ]
