# Generated by Django 4.1.2 on 2022-11-14 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiredAPI', '0011_rename_reciver_message_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_user',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.CreateModel(
            name='TextMessage',
            fields=[
                ('text_message_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wiredAPI.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
