# Generated by Django 4.1.2 on 2022-11-14 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiredAPI', '0012_rename_contact_user_contact_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='contact',
            new_name='reciver',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='contact_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='model_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='model_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
