# Generated by Django 4.1.2 on 2022-11-14 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiredAPI', '0013_rename_contact_message_reciver_remove_contact_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemessage',
            old_name='user',
            new_name='model_user',
        ),
        migrations.RenameField(
            model_name='textmessage',
            old_name='user',
            new_name='model_user',
        ),
        migrations.RenameField(
            model_name='videomessage',
            old_name='user',
            new_name='model_user',
        ),
    ]
