# Generated by Django 4.1.2 on 2022-11-15 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiredAPI', '0015_chat_participant_remove_message_reciver_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
