# Generated by Django 4.1.2 on 2022-11-15 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiredAPI', '0017_participant_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
