# Generated by Django 4.1.2 on 2022-11-18 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiredAPI', '0019_participant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='msg_type',
        ),
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='wiredAPI.chat'),
        ),
    ]
