# Generated by Django 4.1.2 on 2022-11-18 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiredAPI', '0020_remove_message_msg_type_message_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
    ]
